version: '3'

services:
    nginx:
        container_name: nginx
        hostname: nginx
        build: 
            context: ./services/nginx
            dockerfile: Dockerfile
        ports:
            - "80:80"
        networks:
            - appnet
        depends_on:
            - node
    node:
        container_name: node
        hostname: node
        build: 
            context: .
            dockerfile: ./services/node/Dockerfile
        volumes:
            - ./src:/app/src
        env_file:
            - ./env/ormconfig.env
            - ./env/app.env
        networks:
            - appnet
        depends_on:
            - postgres
    postgres:
        container_name: db
        hostname: db
        build: 
            context: ./services/postgres
        restart: always
        volumes:
            - dbdata:/var/lib/postgresql/data
        env_file:
            - ./env/database.env
        networks:
            - appnet
networks:
    appnet:
        driver: bridge
volumes:
    dbdata:
        driver: local